### ISSUE TITLE
exec.Command("cmd.exe", "-c", s)   not work for windows  

### ISSUE THREAD

**Issue by tablecell** [hulkers/m3u8-downloader#2]
func ExecShell(s string) {
	cmd := exec.Command("cmd.exe", "-c", s)   // /bin/shell
	var out bytes.Buffer
	cmd.Stdout = &out
	err := cmd.Run()
	if err != nil {
		panic(err)
	}
	fmt.Printf("%s", out.String())
}

**Comment by sndnvaps** [comment]
```diff
func ExecShell(s string) {
--cmd := exec.Command("cmd.exe", "-c", s) // /bin/shell
+++cmd := exec.Command("cmd.exe", "/C", s) // /bin/shell
var out bytes.Buffer
cmd.Stdout = &out
err := cmd.Run()
if err != nil {
panic(err)
}
fmt.Printf("%s", out.String())
}
```
这样修改才可以的。。

**Comment by tablecell** [comment]
2020/06/19 09:40:19 m3u8.go:291: 下载完成，耗时:13.8092268s
del /Q ad*.tscopy /b *.ts new.tmppanic: exit status 1

goroutine 1 [running]:
main.ExecShell(0x6b2215, 0x14)
        e:/goapp/m3u8.go:190 +0x229
main.win_merge_file(0x11c6a210, 0x23)
        e:/goapp/m3u8.go:210 +0x59
main.Run()
        e:/goapp/m3u8.go:297 +0x708
main.main()
        e:/goapp/m3u8.go:306 +0x17
exit status 2

**Comment by tablecell** [comment]
单独执行是正确的
```
package main 
import ( "fmt"
	"os/exec"
	"bytes"
)



func ExecShell(s string) {
cmd := exec.Command("cmd.exe", "/C", s) // /bin/shell
var out bytes.Buffer
cmd.Stdout = &out
err := cmd.Run()
if err != nil {
panic(err)
}
fmt.Printf("%s", out.String())
}


func main(){


 ExecShell("dir")

}
```

**Comment by sndnvaps** [comment]
你看看当前目录里面有没有生成*.ts文件的文件呢。。 
还有就是操作什么系统是什么呢，我这测试环境为win7 x64, 
在cmd中执行的操作。。。

**Comment by tablecell** [comment]
> 
> 
> @tablecell
> 你看看当前目录里面有没有生成*.ts文件的文件呢。。
> 还有就是操作什么系统是什么呢，我这测试环境为win7 x64,
> 在cmd中执行的操作。。。
> 
> 我对项目进行了修改，你看看有没有帮助
> https://github.com/sndnvaps/m3u8-downloader
 当前目录下只有目录结构，没有文件
└─movie
    ├─index.m3u82006190935
    ├─index.m3u82006190938
    ├─index.m3u82006190940
    └─index.m3u82006192042
os是 win7 32bit 
go version go1.13.12 windows/386

**Comment by sndnvaps** [comment]
> > @tablecell
> > 你看看当前目录里面有没有生成*.ts文件的文件呢。。
> > 还有就是操作什么系统是什么呢，我这测试环境为win7 x64,
> > 在cmd中执行的操作。。。
> > 我对项目进行了修改，你看看有没有帮助
> > https://github.com/sndnvaps/m3u8-downloader
> 
> 当前目录下只有目录结构，没有文件
> └─movie
> ├─index.m3u82006190935
> ├─index.m3u82006190938
> ├─index.m3u82006190940
> └─index.m3u82006192042
> os是 win7 32bit
> go version go1.13.12 windows/386

你用我的代码编译出程序，测试一下有没有这样的问题。。。
或者下载我编译好的程序在Release里面找一找就行了。。

**Comment by tablecell** [comment]
"gopkg.in/urfave/cli.v1"  这个下载不了

**Comment by sndnvaps** [comment]
> "gopkg.in/urfave/cli.v1" 这个下载不了
> 
> ```
> build command-line-arguments: cannot load gopkg.in/urfave/cli.v1: cannot find mo
> dule providing package gopkg.in/urfave/cli.v1
> ```

我这测试没有问题啊。。 。
你再测试一下，我把cli的地址修改为github了。。 
我这边测试没有问题。。。

**Comment by tablecell** [comment]
可以了  
上一个版本是gopkg.in 打不开 
```
正在 Ping gopkg.in [91.189.92.75] 具有 32 字节的数据:
请求超时。
请求超时。
```

**Comment by sndnvaps** [comment]
> 可以了
> 上一个版本是gopkg.in 打不开
> 
> ```
> 正在 Ping gopkg.in [91.189.92.75] 具有 32 字节的数据:
> 请求超时。
> 请求超时。
> ```

可以了，就行。。。
